apiVersion: v1
kind: LimitRange
metadata:
  name: kyma-relaxed
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 32Mi
    max:
      memory: 1536Mi
    type: Container
    
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: kyma-relaxed
spec:
  hard:
    limits.memory: 6Gi
    requests.memory: 4Gi