apiVersion: v1
data:
  mongodb_host: first-mongo-mongodb.d046471.svc.cluster.local
  mongodb_database: kubernetes-dummy
  authentication_database: admin
  mongodb_username: root
kind: ConfigMap
metadata:
  name: mongo-kubernetes-config
  labels:
     app: personservice
     version: "0.0.3"
